version: "3.9"

services:
  postgres:
    image: postgres
    ports:
      - "5666:5432"
    environment:
      - POSTGRES_USER=kekich
      - POSTGRES_PASSWORD=5454
      - POSTGRES_DB=melofy_db
    restart: always